---

- name: Apache server installed
  hosts: webservers 
  become: yes 
  tasks: 
  - yum: name= "{{ item }}" state=installed
    loop:
      - httpd
      - memcache
    tags:
      - packages

  - template: src="templates/index.html.j2" dest="/var/www/html/index.html"
    tags:
      - deploy

  - debug: msg="Always runs"
    tags:
      - always
