---

- name: Apache server installed
  hosts: webservers 
  become: yes 
  tasks: 
  - name: latest Apache version installed 
    yum: 
      name: httpd 
      state: latest
  - name: Apache enabled and running 
    systemd: 
      name: httpd 
      enabled: true 
      state: started
  - name: copy index.html 
    copy: 
      src: index.html 
      dest: /var/www/html/ 
